# Generated by Django 4.1.4 on 2023-01-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='target',
            field=models.IntegerField(default=0, verbose_name='Target'),
        ),
    ]
