# Generated by Django 3.2.15 on 2023-01-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='score',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='分數'),
        ),
    ]
