# Generated by Django 4.1.4 on 2022-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Name')),
                ('subject', models.CharField(max_length=10, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
        ),
    ]
