# Generated by Django 3.2.15 on 2023-01-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230113_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='時間'),
        ),
    ]
